# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b74109cbe1d027941ea66a77db4ca7a9cfbc3223b52b27ed23cbca20983b59a1e68a66e3d7285a1ec88cbaf916b9fb8c1330f3ae4bf9a8e180fefe032bd99a5a

test:
  secret_key_base: aea519b82075b7d13107bd06e38d56decb2e221478033540ce48e1b80a8ce6de9220104b3bfa68d57443ab3b6265619ac1b718382297f897703509f35ea2279a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
